// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package gothicComponents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/gothicframework/core/corewasm"
	"github.com/gothicframework/core/gothiccore"
)

/**
 * `RuntimeScripts` emits the framework's client-runtime <script> tags for the
 * layout <head>. It replaces the previously hardcoded gothic-core / htmx tags so
 * every runtime asset is served from the framework embed via the /_gothic/ route
 * (no longer copied into the project's public/ folder, and no longer loaded from a
 * third-party CDN), and their content-hash cache-busters stay in sync with the
 * framework version automatically.
 *
 * htmx is no longer a separate <script>: it ships INSIDE gothic-core.wasm (installed
 * as window.htmx when the static core boots, then run over the document once the
 * core is ready), so there is nothing to self-host or load from a CDN here.
 *
 * Emitted, in order:
 *   1. gothic-core.js       — shared idempotent client runtime.
 *   2. gothic-core-boot.js  — full-Go static core boot loader (boots core.wasm,
 *                             which installs window.htmx and processes the DOM).
 *   3. provider marker      — ONLY when SigV4Enabled() (GOTHIC_PROVIDER=AWS): a
 *                             static <meta name="gothic-provider" content="AWS">.
 *                             The WASM core's sigv4 extension reads it at boot to
 *                             decide whether to sign requests. See SigV4Enabled.
 *
 * The shared runtime (1) and static core (2) are intentionally NOT deferred: they
 * install the window globals every per-instance WASM bootstrap depends on and must
 * be present before those bootstraps (which arrive lower in the body) run. The
 * provider marker (3) is a plain static <meta> — it holds no requests and runs no
 * script; it merely sits in the parsed SSR <head> so the WASM signer can read it
 * (querySelector) the moment it boots, with zero boot race.
 *
 * Place it in the layout <head> before any per-instance WASM bootstrap.
 */

func RuntimeScripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Gothic WASM shared runtime: installs the idempotent client globals once per page. Must load before any per-instance WASM bootstrap. --><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue("/_gothic/gothic-core.js?v=" + gothiccore.Version())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `runtimeScripts.templ`, Line: 40, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-gothic-core=\"1\"></script><!-- Gothic full-Go static core: prebuilt, type-agnostic RPC/registration hub. Boots once per page, before any component. --><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue("/_gothic/gothic-core-boot.js?v=" + corewasm.Version())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `runtimeScripts.templ`, Line: 42, Col: 69}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-gothic-core-wasm=\"1\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if SigV4Enabled() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- AWS-only (GOTHIC_PROVIDER=AWS): static provider marker read by the WASM core's sigv4 extension to enable in-path request signing (x-amz-content-sha256). A plain <meta> — no script, no request-holding handshake; present in the parsed SSR head before core.wasm boots. --> <meta name=\"gothic-provider\" content=\"AWS\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
