// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package gothicComponents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/gothicframework/core/corewasm"
	"github.com/gothicframework/core/gothiccore"
	"github.com/gothicframework/core/vendorjs"
)

/**
 * `RuntimeScripts` emits the framework's client-runtime <script> tags for the
 * layout <head>. It replaces the previously hardcoded gothic-core / htmx tags so
 * every runtime asset — including HTMX and its amz-content-sha256 extension — is
 * served from the framework embed via the /_gothic/ route (no longer copied into
 * the project's public/ folder, and no longer loaded from a third-party CDN), and
 * their content-hash cache-busters stay in sync with the framework version
 * automatically.
 *
 * Emitted, in order:
 *   1. gothic-core.js       — shared idempotent client runtime (Phase 15).
 *   2. gothic-core-boot.js  — full-Go static core boot loader (Phase 16).
 *   3. htmx (self-hosted, deferred).
 *   4. amz-content-sha256 HTMX extension (self-hosted, deferred).
 *
 * htmx (and its extension) are loaded `defer` and self-hosted under /_gothic/:
 * `defer` keeps them off the render-blocking critical path (they run in document
 * order right before DOMContentLoaded, which is when htmx initializes anyway), and
 * self-hosting removes the cross-origin DNS/TLS/connection cost to unpkg.com. Both
 * inherit the /_gothic/ handler's immutable caching + on-the-wire br/gzip.
 *
 * The shared runtime (1) and static core (2) are intentionally NOT deferred: they
 * install the window globals every per-instance WASM bootstrap depends on and must
 * be present before those bootstraps (which arrive lower in the body) run.
 *
 * Place it in the layout <head> before any per-instance WASM bootstrap.
 */

func RuntimeScripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Gothic WASM shared runtime: installs the idempotent client globals once per page (Phase 15). Must load before any per-instance WASM bootstrap. --><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue("/_gothic/gothic-core.js?v=" + gothiccore.Version())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `runtimeScripts.templ`, Line: 38, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-gothic-core=\"1\"></script><!-- Gothic full-Go static core (Phase 16): prebuilt, type-agnostic RPC/registration hub. Boots once per page, before any component. --><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue("/_gothic/gothic-core-boot.js?v=" + corewasm.Version())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `runtimeScripts.templ`, Line: 40, Col: 69}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-gothic-core-wasm=\"1\"></script><!-- HTMX + the amz-content-sha256 extension, self-hosted and deferred (no render-blocking third-party request). --><script defer src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue("/_gothic/" + vendorjs.HtmxFileName + "?v=" + vendorjs.HtmxVersion())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `runtimeScripts.templ`, Line: 42, Col: 89}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"></script><script defer src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue("/_gothic/" + vendorjs.AmzExtFileName + "?v=" + vendorjs.AmzExtVersion())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `runtimeScripts.templ`, Line: 43, Col: 93}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
